// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSSRAX2-z6UUb1BIdx2innn-NbJ6mrSoA',
    appId: '1:676340675676:web:41b08d0b6b1e44fa976299',
    messagingSenderId: '676340675676',
    projectId: 'todo-realtime-app',
    authDomain: 'todo-realtime-app.firebaseapp.com',
    storageBucket: 'todo-realtime-app.firebasestorage.app',
    measurementId: 'G-0ZFVJRCQ97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbjIQSv_TEteEKnssDuFvqbCMZEnq3SZg',
    appId: '1:676340675676:android:c44e70ebd42f6c5e976299',
    messagingSenderId: '676340675676',
    projectId: 'todo-realtime-app',
    storageBucket: 'todo-realtime-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqaFs8jxYk-2FG4TdittP0EK6ntq3as8k',
    appId: '1:676340675676:ios:af6b31de84f9f77d976299',
    messagingSenderId: '676340675676',
    projectId: 'todo-realtime-app',
    storageBucket: 'todo-realtime-app.firebasestorage.app',
    iosBundleId: 'com.murlidhar.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqaFs8jxYk-2FG4TdittP0EK6ntq3as8k',
    appId: '1:676340675676:ios:af6b31de84f9f77d976299',
    messagingSenderId: '676340675676',
    projectId: 'todo-realtime-app',
    storageBucket: 'todo-realtime-app.firebasestorage.app',
    iosBundleId: 'com.murlidhar.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSSRAX2-z6UUb1BIdx2innn-NbJ6mrSoA',
    appId: '1:676340675676:web:fe032df212cd14cb976299',
    messagingSenderId: '676340675676',
    projectId: 'todo-realtime-app',
    authDomain: 'todo-realtime-app.firebaseapp.com',
    storageBucket: 'todo-realtime-app.firebasestorage.app',
    measurementId: 'G-76SHS4SZNN',
  );
}
